name: UI ENV Hello World

on: push

jobs:
  env-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print UI variables
        run: |
          echo "Message 1: ${{ vars.UI_MESSAGE }}"
          echo "Message 2: ${{ vars.UI_MESSAGE2 }}"
