name: UI ENV Hello World

on: push

jobs:
  env-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print UI env variables
        run: |
          echo "Message: $UI_MESSAGE"
          echo "Message: $UI_MESSAGE2"
